-- Catalog tables + notification prefs. Seeded from src/data/*.ts.
alter table public.profiles add column if not exists notification_prefs jsonb not null default '{"renewals":true,"readiness":true,"utilization":true,"reviews":true}'::jsonb;

create table if not exists public.issuers (
  id text primary key,
  name text not null,
  accent_color text not null,
  application_rules jsonb not null default '[]'::jsonb,
  contact jsonb not null
);
create table if not exists public.transfer_partners (
  id text primary key,
  name text not null,
  type text not null,
  transfers_from jsonb not null default '[]'::jsonb
);
create table if not exists public.cards (
  id text primary key,
  issuer_id text not null references public.issuers (id),
  name text not null,
  annual_fee integer not null,
  product jsonb not null
);
alter table public.issuers enable row level security;
alter table public.transfer_partners enable row level security;
alter table public.cards enable row level security;
drop policy if exists issuers_select_public on public.issuers;
create policy issuers_select_public on public.issuers for select to anon, authenticated using (true);
grant select on table public.issuers to anon, authenticated;
revoke insert, update, delete on table public.issuers from anon, authenticated;
drop policy if exists transfer_partners_select_public on public.transfer_partners;
create policy transfer_partners_select_public on public.transfer_partners for select to anon, authenticated using (true);
grant select on table public.transfer_partners to anon, authenticated;
revoke insert, update, delete on table public.transfer_partners from anon, authenticated;
drop policy if exists cards_select_public on public.cards;
create policy cards_select_public on public.cards for select to anon, authenticated using (true);
grant select on table public.cards to anon, authenticated;
revoke insert, update, delete on table public.cards from anon, authenticated;
insert into public.issuers (id, name, accent_color, application_rules, contact) values
  ('chase', 'Chase', '#0A3E6E', '["Chase''s unwritten \"5/24\" rule: applicants who have opened 5+ personal credit cards (any issuer) in the past 24 months are typically declined for most Chase cards.","Chase generally limits applicants to one Sapphire-family card at a time, and restricts new-cardmember bonuses if you''ve earned one on the same card in the last 48 months."]'::jsonb, '{"customerService":"1-800-935-9935","fraud":"1-800-955-9060","lostStolen":"1-800-935-9935","website":"https://www.chase.com"}'::jsonb),
  ('capital_one', 'Capital One', '#8B1D2C', '["Capital One generally limits most individuals to two personal credit cards at a time, and there are informal limits on new-account velocity (often described as one new card roughly every 6 months).","Capital One typically will not approve a new card if you already carry a card with substantially overlapping benefits."]'::jsonb, '{"customerService":"1-800-227-4825","fraud":"1-800-227-4825","lostStolen":"1-800-227-4825","website":"https://www.capitalone.com"}'::jsonb),
  ('amex', 'American Express', '#016FD0', '["Amex''s \"once per lifetime\" rule generally prevents earning a welcome offer on the same card again if you''ve ever held it.","Amex evaluates total available credit across all your Amex cards, which can affect approval odds and credit limits on new applications."]'::jsonb, '{"customerService":"1-800-528-4800","fraud":"1-800-528-2122","lostStolen":"1-800-528-4800","website":"https://www.americanexpress.com"}'::jsonb),
  ('citi', 'Citi', '#003B7A', '["Citi generally limits applicants to one new personal credit card roughly every 8 days across all Citi applications, and restricts welcome bonuses if you currently hold or recently closed the same card."]'::jsonb, '{"customerService":"1-800-950-5114","fraud":"1-800-950-5114","lostStolen":"1-800-950-5114","website":"https://www.citi.com"}'::jsonb),
  ('bank_of_america', 'Bank of America', '#012169', '["Bank of America uses an informal \"2/3/4\" rule: generally no more than 2 new cards in 2 months, 3 in 12 months, or 4 in 24 months across all issuers.","Preferred Rewards banking clients can earn a 25\u201375% rewards bonus on eligible Bank of America credit cards."]'::jsonb, '{"customerService":"1-800-732-9194","fraud":"1-800-732-9194","lostStolen":"1-800-732-9194","website":"https://www.bankofamerica.com"}'::jsonb),
  ('wells_fargo', 'Wells Fargo', '#D71E28', '["Wells Fargo generally allows only one new personal credit card application every 6 months."]'::jsonb, '{"customerService":"1-800-869-3557","fraud":"1-800-869-3557","lostStolen":"1-800-869-3557","website":"https://www.wellsfargo.com"}'::jsonb),
  ('us_bank', 'U.S. Bank', '#0C2074', '["U.S. Bank evaluates recent inquiries and existing relationship depth on every application."]'::jsonb, '{"customerService":"1-800-285-8585","fraud":"1-800-347-7378","lostStolen":"1-800-285-8585","website":"https://www.usbank.com"}'::jsonb),
  ('discover', 'Discover', '#F76B1C', '["Discover generally allows only one Discover card per person at a time."]'::jsonb, '{"customerService":"1-800-347-2683","fraud":"1-800-347-2683","lostStolen":"1-800-347-2683","website":"https://www.discover.com"}'::jsonb)
on conflict (id) do update set name = excluded.name, accent_color = excluded.accent_color, application_rules = excluded.application_rules, contact = excluded.contact;
insert into public.transfer_partners (id, name, type, transfers_from) values
  ('united', 'United MileagePlus', 'airline', '[{"rewardsCurrency":"chase_ur","ratio":"1:1"}]'::jsonb),
  ('southwest', 'Southwest Rapid Rewards', 'airline', '[{"rewardsCurrency":"chase_ur","ratio":"1:1"}]'::jsonb),
  ('air_canada', 'Air Canada Aeroplan', 'airline', '[{"rewardsCurrency":"chase_ur","ratio":"1:1"},{"rewardsCurrency":"amex_mr","ratio":"1:1"}]'::jsonb),
  ('air_france_klm', 'Air France-KLM Flying Blue', 'airline', '[{"rewardsCurrency":"amex_mr","ratio":"1:1"},{"rewardsCurrency":"citi_thankyou","ratio":"1:1"},{"rewardsCurrency":"capital_one_miles","ratio":"1:1"}]'::jsonb),
  ('british_airways', 'British Airways Executive Club', 'airline', '[{"rewardsCurrency":"chase_ur","ratio":"1:1"},{"rewardsCurrency":"amex_mr","ratio":"1:1"},{"rewardsCurrency":"capital_one_miles","ratio":"1:1"}]'::jsonb),
  ('emirates', 'Emirates Skywards', 'airline', '[{"rewardsCurrency":"amex_mr","ratio":"1:1"},{"rewardsCurrency":"capital_one_miles","ratio":"1:1"}]'::jsonb),
  ('virgin_atlantic', 'Virgin Atlantic Flying Club', 'airline', '[{"rewardsCurrency":"chase_ur","ratio":"1:1"},{"rewardsCurrency":"amex_mr","ratio":"1:1"},{"rewardsCurrency":"capital_one_miles","ratio":"1:1"}]'::jsonb),
  ('delta', 'Delta SkyMiles', 'airline', '[{"rewardsCurrency":"amex_mr","ratio":"1:1"}]'::jsonb),
  ('jetblue', 'JetBlue TrueBlue', 'airline', '[{"rewardsCurrency":"citi_thankyou","ratio":"1:1"}]'::jsonb),
  ('marriott', 'Marriott Bonvoy', 'hotel', '[{"rewardsCurrency":"amex_mr","ratio":"1:1"},{"rewardsCurrency":"chase_ur","ratio":"1:1"}]'::jsonb),
  ('hyatt', 'World of Hyatt', 'hotel', '[{"rewardsCurrency":"chase_ur","ratio":"1:1"}]'::jsonb),
  ('hilton', 'Hilton Honors', 'hotel', '[{"rewardsCurrency":"amex_mr","ratio":"1:2"}]'::jsonb),
  ('choice', 'Choice Privileges', 'hotel', '[{"rewardsCurrency":"capital_one_miles","ratio":"1:1"}]'::jsonb),
  ('wyndham', 'Wyndham Rewards', 'hotel', '[{"rewardsCurrency":"capital_one_miles","ratio":"1:1"}]'::jsonb)
on conflict (id) do update set name = excluded.name, type = excluded.type, transfers_from = excluded.transfers_from;
insert into public.cards (id, issuer_id, name, annual_fee, product) values
  ('capital_one_platinum_secured', 'capital_one', 'Capital One Platinum Secured', 0, '{"id":"capital_one_platinum_secured","name":"Capital One Platinum Secured","issuerId":"capital_one","network":"mastercard","category":["student"],"annualFee":0,"rewardsCurrency":"cashback","baseRewardRate":0,"rewardCategories":[],"welcomeOffer":{"description":"No welcome bonus \u2014 a credit-building tool, not a rewards card","spendRequirement":0,"timeframeMonths":0},"benefits":[{"label":"Credit-building focus","description":"Reports monthly to all three bureaus to help establish payment history."},{"label":"Refundable security deposit","description":"Deposit as low as $49\u2013$200 depending on approval, sets your starting credit line."},{"label":"Automatic reviews","description":"Capital One reviews the account for credit-line increases and unsecured upgrades."}],"loungeAccess":[],"travelProtections":[],"transferPartnerIds":[],"eligibility":{"minCreditScoreBand":"no_credit","minCreditAgeMonths":0,"maxRecentInquiries6mo":6,"incomeGuidance":"Any verifiable income, including allowance or benefits, is generally acceptable.","issuerRules":["Requires a refundable security deposit to open."],"notes":"Designed for first-time credit users or those rebuilding credit."},"productChangeTargets":["capital_one_quicksilver"],"applicationUrl":"https://www.capitalone.com/credit-cards/platinum-secured/","dataFreshness":{"lastVerified":"2025-06-01","source":"Issuer public product pages (manually compiled)","confidence":"medium"}}'::jsonb),
  ('capital_one_quicksilver', 'capital_one', 'Capital One Quicksilver', 0, '{"id":"capital_one_quicksilver","name":"Capital One Quicksilver","issuerId":"capital_one","network":"mastercard","category":["cash_back"],"annualFee":0,"rewardsCurrency":"cashback","baseRewardRate":1.5,"rewardCategories":[{"category":"everything","multiplier":1.5}],"welcomeOffer":{"description":"One-time cash bonus after meeting minimum spend","spendRequirement":500,"timeframeMonths":3},"benefits":[{"label":"Flat-rate cash back","description":"1.5% on every purchase, no rotating categories to track."},{"label":"No annual fee","description":"Keep it open indefinitely to anchor your average account age."}],"loungeAccess":[],"travelProtections":["Extended warranty","Travel accident insurance"],"transferPartnerIds":[],"eligibility":{"minCreditScoreBand":"fair","minCreditAgeMonths":6,"maxRecentInquiries6mo":4,"incomeGuidance":"Steady income sufficient to cover a modest credit line.","issuerRules":["Capital One generally limits most individuals to two personal cards at a time."],"notes":"A common first unsecured card and a low-maintenance long-term keeper."},"productChangeTargets":[],"applicationUrl":"https://www.capitalone.com/credit-cards/quicksilver/","dataFreshness":{"lastVerified":"2025-06-01","source":"Issuer public product pages (manually compiled)","confidence":"medium"}}'::jsonb),
  ('capital_one_savorone', 'capital_one', 'Capital One SavorOne', 0, '{"id":"capital_one_savorone","name":"Capital One SavorOne","issuerId":"capital_one","network":"mastercard","category":["cash_back"],"annualFee":0,"rewardsCurrency":"cashback","baseRewardRate":1,"rewardCategories":[{"category":"dining","multiplier":3},{"category":"groceries","multiplier":3},{"category":"entertainment","multiplier":3},{"category":"streaming","multiplier":3}],"welcomeOffer":{"description":"One-time cash bonus after meeting minimum spend","spendRequirement":500,"timeframeMonths":3},"benefits":[{"label":"No annual fee","description":"Strong ongoing value with no cost to keep the account open."},{"label":"Dining & entertainment focus","description":"3% back on categories most households spend in every month."}],"loungeAccess":[],"travelProtections":["Extended warranty"],"transferPartnerIds":[],"eligibility":{"minCreditScoreBand":"fair","minCreditAgeMonths":6,"maxRecentInquiries6mo":4,"incomeGuidance":"Steady income sufficient to cover a modest credit line.","issuerRules":["Capital One generally limits most individuals to two personal cards at a time."],"notes":"A strong entry point into the Capital One ecosystem for dining/grocery-heavy spenders."},"productChangeTargets":["capital_one_savor"],"applicationUrl":"https://www.capitalone.com/credit-cards/savorone/","dataFreshness":{"lastVerified":"2025-06-01","source":"Issuer public product pages (manually compiled)","confidence":"medium"}}'::jsonb),
  ('capital_one_savor', 'capital_one', 'Capital One Savor', 95, '{"id":"capital_one_savor","name":"Capital One Savor","issuerId":"capital_one","network":"mastercard","category":["cash_back"],"annualFee":95,"rewardsCurrency":"cashback","baseRewardRate":1,"rewardCategories":[{"category":"dining","multiplier":4},{"category":"entertainment","multiplier":4},{"category":"groceries","multiplier":3},{"category":"streaming","multiplier":4}],"welcomeOffer":{"description":"One-time cash bonus after meeting minimum spend","spendRequirement":500,"timeframeMonths":3},"benefits":[{"label":"Elevated dining & entertainment","description":"4% back on dining, entertainment, and popular streaming services."},{"label":"Statement credits","description":"Periodic entertainment/dining statement-credit offers."}],"loungeAccess":[],"travelProtections":["Extended warranty","Travel accident insurance"],"transferPartnerIds":[],"eligibility":{"minCreditScoreBand":"good","minCreditAgeMonths":18,"maxRecentInquiries6mo":3,"incomeGuidance":"Sufficient discretionary income to justify the annual fee via dining/entertainment spend.","issuerRules":["Capital One generally limits most individuals to two personal cards at a time."],"notes":"Best for established dining/entertainment spenders already comfortable with Capital One."},"productChangeTargets":[],"applicationUrl":"https://www.capitalone.com/credit-cards/savor/","dataFreshness":{"lastVerified":"2025-06-01","source":"Issuer public product pages (manually compiled)","confidence":"medium"}}'::jsonb),
  ('capital_one_venture', 'capital_one', 'Capital One Venture', 95, '{"id":"capital_one_venture","name":"Capital One Venture","issuerId":"capital_one","network":"visa","category":["travel"],"annualFee":95,"rewardsCurrency":"capital_one_miles","baseRewardRate":2,"rewardCategories":[{"category":"everything","multiplier":2},{"category":"hotels_rental_cars_via_portal","multiplier":5}],"welcomeOffer":{"description":"One-time bonus miles after meeting minimum spend","spendRequirement":4000,"timeframeMonths":3},"benefits":[{"label":"Flat-rate travel miles","description":"2x miles on every purchase \u2014 simple to maximize without tracking categories."},{"label":"Global Entry/TSA PreCheck credit","description":"Statement credit toward Global Entry or TSA PreCheck application fee."}],"loungeAccess":[],"travelProtections":["Rental car insurance","Travel accident insurance"],"transferPartnerIds":["air_canada","air_france_klm","british_airways","emirates","virgin_atlantic","choice","wyndham"],"eligibility":{"minCreditScoreBand":"good","minCreditAgeMonths":18,"maxRecentInquiries6mo":3,"incomeGuidance":"Income sufficient to comfortably justify a mid-tier travel card.","issuerRules":["Capital One generally limits most individuals to two personal cards at a time."],"notes":"A common stepping-stone toward Venture X once profile and Capital One history are stronger."},"productChangeTargets":["capital_one_venture_x"],"applicationUrl":"https://www.capitalone.com/credit-cards/venture/","dataFreshness":{"lastVerified":"2025-06-01","source":"Issuer public product pages (manually compiled)","confidence":"medium"}}'::jsonb),
  ('capital_one_venture_x', 'capital_one', 'Capital One Venture X', 395, '{"id":"capital_one_venture_x","name":"Capital One Venture X","issuerId":"capital_one","network":"visa","category":["premium_travel"],"annualFee":395,"rewardsCurrency":"capital_one_miles","baseRewardRate":2,"rewardCategories":[{"category":"everything","multiplier":2},{"category":"flights_hotels_via_portal","multiplier":5}],"welcomeOffer":{"description":"Large one-time bonus miles after meeting minimum spend","spendRequirement":4000,"timeframeMonths":3},"benefits":[{"label":"$300 annual travel credit","description":"Statement credit for bookings made through Capital One Travel."},{"label":"10,000-mile anniversary bonus","description":"Bonus miles every account anniversary, worth roughly $100."},{"label":"Priority Pass lounge access","description":"Unlimited access for cardholder and authorized guests."},{"label":"Global Entry/TSA PreCheck credit","description":"Statement credit toward application fee."}],"loungeAccess":["Capital One Lounges","Priority Pass"],"travelProtections":["Trip cancellation/interruption","Rental car insurance","Trip delay reimbursement"],"transferPartnerIds":["air_canada","air_france_klm","british_airways","emirates","virgin_atlantic","choice","wyndham"],"eligibility":{"minCreditScoreBand":"very_good","minCreditAgeMonths":36,"maxRecentInquiries6mo":2,"incomeGuidance":"Income that comfortably supports a premium annual fee and reflects the credit line requested.","issuerRules":["Capital One generally limits most individuals to two personal cards at a time.","Existing, positive Capital One relationship and account history are commonly cited as helpful for approval."],"notes":"A top-tier premium travel card \u2014 profile strength and existing issuer relationship matter more than for entry-level products."},"productChangeTargets":[],"applicationUrl":"https://www.capitalone.com/credit-cards/venture-x/","dataFreshness":{"lastVerified":"2025-06-01","source":"Issuer public product pages (manually compiled)","confidence":"medium"}}'::jsonb),
  ('chase_freedom_unlimited', 'chase', 'Chase Freedom Unlimited', 0, '{"id":"chase_freedom_unlimited","name":"Chase Freedom Unlimited","issuerId":"chase","network":"visa","category":["cash_back"],"annualFee":0,"rewardsCurrency":"chase_ur","baseRewardRate":1.5,"rewardCategories":[{"category":"dining","multiplier":3},{"category":"drugstore","multiplier":3},{"category":"everything","multiplier":1.5}],"welcomeOffer":{"description":"Cash bonus (as Ultimate Rewards points) after minimum spend","spendRequirement":500,"timeframeMonths":3},"benefits":[{"label":"No annual fee","description":"Strong flat-rate earner to anchor a Chase portfolio."},{"label":"Pairs with Sapphire","description":"Points can be combined with a Sapphire card to unlock travel-transfer value."}],"loungeAccess":[],"travelProtections":["Purchase protection","Extended warranty"],"transferPartnerIds":[],"eligibility":{"minCreditScoreBand":"good","minCreditAgeMonths":12,"maxRecentInquiries6mo":4,"incomeGuidance":"Steady income sufficient to cover a modest credit line.","issuerRules":["Subject to Chase''s 5/24 rule (5+ new cards in 24 months across all issuers may cause a decline)."],"notes":"A common Chase-ecosystem starter card that pairs well with Sapphire Preferred/Reserve later."},"productChangeTargets":[],"applicationUrl":"https://creditcards.chase.com/cash-back-credit-cards/freedom/unlimited","dataFreshness":{"lastVerified":"2025-06-01","source":"Issuer public product pages (manually compiled)","confidence":"medium"}}'::jsonb),
  ('chase_freedom_flex', 'chase', 'Chase Freedom Flex', 0, '{"id":"chase_freedom_flex","name":"Chase Freedom Flex","issuerId":"chase","network":"mastercard","category":["cash_back"],"annualFee":0,"rewardsCurrency":"chase_ur","baseRewardRate":1,"rewardCategories":[{"category":"rotating","multiplier":5,"cap":1500,"notes":"5% on quarterly-activated rotating categories"},{"category":"dining","multiplier":3},{"category":"drugstore","multiplier":3},{"category":"everything","multiplier":1}],"welcomeOffer":{"description":"Cash bonus (as Ultimate Rewards points) after minimum spend","spendRequirement":500,"timeframeMonths":3},"benefits":[{"label":"Rotating 5% categories","description":"Quarterly activation unlocks 5% cash back up to the quarterly cap."}],"loungeAccess":[],"travelProtections":["Purchase protection","Extended warranty"],"transferPartnerIds":[],"eligibility":{"minCreditScoreBand":"good","minCreditAgeMonths":12,"maxRecentInquiries6mo":4,"incomeGuidance":"Steady income sufficient to cover a modest credit line.","issuerRules":["Subject to Chase''s 5/24 rule."],"notes":"Best for those willing to track and activate rotating categories each quarter."},"productChangeTargets":[],"applicationUrl":"https://creditcards.chase.com/cash-back-credit-cards/freedom/flex","dataFreshness":{"lastVerified":"2025-06-01","source":"Issuer public product pages (manually compiled)","confidence":"medium"}}'::jsonb),
  ('chase_sapphire_preferred', 'chase', 'Chase Sapphire Preferred', 95, '{"id":"chase_sapphire_preferred","name":"Chase Sapphire Preferred","issuerId":"chase","network":"visa","category":["travel"],"annualFee":95,"rewardsCurrency":"chase_ur","baseRewardRate":1,"rewardCategories":[{"category":"travel_via_portal","multiplier":5},{"category":"dining","multiplier":3},{"category":"streaming","multiplier":3},{"category":"everything","multiplier":1}],"welcomeOffer":{"description":"Large one-time bonus points after minimum spend","spendRequirement":4000,"timeframeMonths":3},"benefits":[{"label":"25% more value via Chase Travel","description":"Points redeemed for travel through Chase are worth 25% more."},{"label":"Full transfer-partner access","description":"1:1 transfers to Chase''s full airline and hotel partner list."},{"label":"Primary rental car insurance","description":"Covers rental cars as primary insurance, not secondary."}],"loungeAccess":[],"travelProtections":["Trip cancellation/interruption","Primary rental car insurance","Trip delay reimbursement","Baggage delay insurance"],"transferPartnerIds":["united","southwest","air_canada","air_france_klm","british_airways","virgin_atlantic","marriott","hyatt"],"eligibility":{"minCreditScoreBand":"good","minCreditAgeMonths":18,"maxRecentInquiries6mo":3,"incomeGuidance":"Income sufficient to comfortably justify a mid-tier travel card.","issuerRules":["Subject to Chase''s 5/24 rule.","Generally one Sapphire-family card at a time."],"notes":"The most common entry point into the Chase transferable-points ecosystem."},"productChangeTargets":["chase_sapphire_reserve"],"applicationUrl":"https://creditcards.chase.com/travel-credit-cards/sapphire/preferred","dataFreshness":{"lastVerified":"2025-06-01","source":"Issuer public product pages (manually compiled)","confidence":"medium"}}'::jsonb),
  ('chase_sapphire_reserve', 'chase', 'Chase Sapphire Reserve', 550, '{"id":"chase_sapphire_reserve","name":"Chase Sapphire Reserve","issuerId":"chase","network":"visa","category":["premium_travel"],"annualFee":550,"rewardsCurrency":"chase_ur","baseRewardRate":1,"rewardCategories":[{"category":"travel_via_portal","multiplier":10},{"category":"dining","multiplier":3},{"category":"everything","multiplier":1}],"welcomeOffer":{"description":"Large one-time bonus points after minimum spend","spendRequirement":4000,"timeframeMonths":3},"benefits":[{"label":"$300 annual travel credit","description":"Broad statement credit toward travel purchases."},{"label":"Priority Pass lounge access","description":"Unlimited visits for cardholder and guests."},{"label":"50% more value via Chase Travel","description":"Points redeemed for travel through Chase are worth 50% more."}],"loungeAccess":["Chase Sapphire Lounges","Priority Pass"],"travelProtections":["Trip cancellation/interruption","Primary rental car insurance","Trip delay reimbursement","Baggage delay insurance"],"transferPartnerIds":["united","southwest","air_canada","air_france_klm","british_airways","virgin_atlantic","marriott","hyatt"],"eligibility":{"minCreditScoreBand":"very_good","minCreditAgeMonths":36,"maxRecentInquiries6mo":2,"incomeGuidance":"Income that comfortably supports a premium annual fee.","issuerRules":["Subject to Chase''s 5/24 rule.","Generally one Sapphire-family card at a time."],"notes":"Top-tier Chase premium travel card; strongest fit once profile is well-established."},"productChangeTargets":[],"applicationUrl":"https://creditcards.chase.com/travel-credit-cards/sapphire/reserve","dataFreshness":{"lastVerified":"2025-06-01","source":"Issuer public product pages (manually compiled)","confidence":"medium"}}'::jsonb),
  ('amex_blue_cash_everyday', 'amex', 'Amex Blue Cash Everyday', 0, '{"id":"amex_blue_cash_everyday","name":"Amex Blue Cash Everyday","issuerId":"amex","network":"amex","category":["cash_back"],"annualFee":0,"rewardsCurrency":"cashback","baseRewardRate":1,"rewardCategories":[{"category":"groceries","multiplier":3,"cap":6000},{"category":"online_retail","multiplier":3},{"category":"gas","multiplier":3}],"welcomeOffer":{"description":"Statement-credit bonus after minimum spend","spendRequirement":2000,"timeframeMonths":6},"benefits":[{"label":"No annual fee","description":"Solid everyday-category earner with no ongoing cost."}],"loungeAccess":[],"travelProtections":[],"transferPartnerIds":[],"eligibility":{"minCreditScoreBand":"good","minCreditAgeMonths":12,"maxRecentInquiries6mo":4,"incomeGuidance":"Steady income sufficient to cover a modest credit line.","issuerRules":["Amex evaluates total credit exposure across all your existing Amex cards."],"notes":"A low-commitment way to establish an Amex relationship before Gold/Platinum."},"productChangeTargets":["amex_blue_cash_preferred"],"applicationUrl":"https://www.americanexpress.com/us/credit-cards/card/blue-cash-everyday/","dataFreshness":{"lastVerified":"2025-06-01","source":"Issuer public product pages (manually compiled)","confidence":"medium"}}'::jsonb),
  ('amex_blue_cash_preferred', 'amex', 'Amex Blue Cash Preferred', 95, '{"id":"amex_blue_cash_preferred","name":"Amex Blue Cash Preferred","issuerId":"amex","network":"amex","category":["cash_back"],"annualFee":95,"rewardsCurrency":"cashback","baseRewardRate":1,"rewardCategories":[{"category":"groceries","multiplier":6,"cap":6000},{"category":"streaming","multiplier":6},{"category":"gas","multiplier":3}],"welcomeOffer":{"description":"Statement-credit bonus after minimum spend","spendRequirement":3000,"timeframeMonths":6},"benefits":[{"label":"Highest grocery cash-back rate","description":"6% at U.S. supermarkets, up to the annual cap."}],"loungeAccess":[],"travelProtections":[],"transferPartnerIds":[],"eligibility":{"minCreditScoreBand":"good","minCreditAgeMonths":18,"maxRecentInquiries6mo":3,"incomeGuidance":"Sufficient discretionary income to justify the annual fee via grocery spend.","issuerRules":["Amex evaluates total credit exposure across all your existing Amex cards."],"notes":"Best for households with high grocery spend."},"productChangeTargets":[],"applicationUrl":"https://www.americanexpress.com/us/credit-cards/card/blue-cash-preferred/","dataFreshness":{"lastVerified":"2025-06-01","source":"Issuer public product pages (manually compiled)","confidence":"medium"}}'::jsonb),
  ('amex_gold', 'amex', 'American Express Gold Card', 325, '{"id":"amex_gold","name":"American Express Gold Card","issuerId":"amex","network":"amex","category":["travel"],"annualFee":325,"rewardsCurrency":"amex_mr","baseRewardRate":1,"rewardCategories":[{"category":"dining","multiplier":4,"cap":50000},{"category":"groceries","multiplier":4,"cap":25000},{"category":"flights","multiplier":3}],"welcomeOffer":{"description":"Large one-time bonus points after minimum spend","spendRequirement":6000,"timeframeMonths":6},"benefits":[{"label":"Dining & grocery credits","description":"Monthly statement credits at select dining and grocery partners."},{"label":"Full Membership Rewards transfer partners","description":"1:1 transfers to Amex''s airline and hotel partners."}],"loungeAccess":[],"travelProtections":["Baggage insurance","Car rental loss and damage insurance"],"transferPartnerIds":["air_canada","air_france_klm","british_airways","emirates","virgin_atlantic","delta","marriott","hilton"],"eligibility":{"minCreditScoreBand":"good","minCreditAgeMonths":24,"maxRecentInquiries6mo":3,"incomeGuidance":"Income sufficient to comfortably justify the annual fee, offset partly by dining/grocery credits.","issuerRules":["Amex welcome-offer eligibility generally requires never having held the card before.","Amex evaluates total credit exposure across all your existing Amex cards."],"notes":"The most popular Amex Membership Rewards earner for dining and grocery-heavy households."},"productChangeTargets":["amex_platinum"],"applicationUrl":"https://www.americanexpress.com/us/credit-cards/card/gold-card/","dataFreshness":{"lastVerified":"2025-06-01","source":"Issuer public product pages (manually compiled)","confidence":"medium"}}'::jsonb),
  ('amex_platinum', 'amex', 'The Platinum Card from American Express', 695, '{"id":"amex_platinum","name":"The Platinum Card from American Express","issuerId":"amex","network":"amex","category":["premium_travel"],"annualFee":695,"rewardsCurrency":"amex_mr","baseRewardRate":1,"rewardCategories":[{"category":"flights_via_portal","multiplier":5},{"category":"hotels_via_portal","multiplier":5}],"welcomeOffer":{"description":"Large one-time bonus points after minimum spend","spendRequirement":8000,"timeframeMonths":6},"benefits":[{"label":"Extensive lounge network","description":"Centurion Lounge, Priority Pass, Delta Sky Club (with eligible flight), and airline-specific lounges."},{"label":"Broad statement credits","description":"A large set of partner statement credits covering travel, dining, and entertainment categories."},{"label":"Elite hotel status","description":"Automatic Gold status with Marriott Bonvoy and Hilton Honors."}],"loungeAccess":["Centurion Lounge","Priority Pass","Delta Sky Club (restrictions apply)","Airline lounges"],"travelProtections":["Trip cancellation/interruption","Baggage insurance","Car rental loss and damage insurance"],"transferPartnerIds":["air_canada","air_france_klm","british_airways","emirates","virgin_atlantic","delta","marriott","hilton"],"eligibility":{"minCreditScoreBand":"very_good","minCreditAgeMonths":36,"maxRecentInquiries6mo":2,"incomeGuidance":"Income that comfortably supports a premium annual fee, ideally offset by the statement-credit ecosystem.","issuerRules":["Amex welcome-offer eligibility generally requires never having held the card before.","Amex evaluates total credit exposure across all your existing Amex cards."],"notes":"The credits only offset the fee if you''ll actually use the specific partner services \u2014 evaluate fit carefully."},"productChangeTargets":[],"applicationUrl":"https://www.americanexpress.com/us/credit-cards/card/platinum/","dataFreshness":{"lastVerified":"2025-06-01","source":"Issuer public product pages (manually compiled)","confidence":"medium"}}'::jsonb),
  ('citi_double_cash', 'citi', 'Citi Double Cash', 0, '{"id":"citi_double_cash","name":"Citi Double Cash","issuerId":"citi","network":"mastercard","category":["cash_back"],"annualFee":0,"rewardsCurrency":"citi_thankyou","baseRewardRate":2,"rewardCategories":[{"category":"everything","multiplier":2,"notes":"1% on purchase, 1% when paid off"}],"welcomeOffer":{"description":"Cash bonus after minimum spend","spendRequirement":1500,"timeframeMonths":6},"benefits":[{"label":"Simple flat 2%","description":"Among the highest flat-rate cash-back cards with no annual fee."}],"loungeAccess":[],"travelProtections":[],"transferPartnerIds":[],"eligibility":{"minCreditScoreBand":"good","minCreditAgeMonths":12,"maxRecentInquiries6mo":4,"incomeGuidance":"Steady income sufficient to cover a modest credit line.","issuerRules":["Citi generally limits new personal-card applications to roughly one per 8 days across all Citi cards."],"notes":"A reliable long-term flat-rate keeper."},"productChangeTargets":[],"applicationUrl":"https://www.citi.com/credit-cards/citi-double-cash-credit-card","dataFreshness":{"lastVerified":"2025-06-01","source":"Issuer public product pages (manually compiled)","confidence":"medium"}}'::jsonb),
  ('citi_custom_cash', 'citi', 'Citi Custom Cash', 0, '{"id":"citi_custom_cash","name":"Citi Custom Cash","issuerId":"citi","network":"mastercard","category":["cash_back"],"annualFee":0,"rewardsCurrency":"citi_thankyou","baseRewardRate":1,"rewardCategories":[{"category":"top_spend_category","multiplier":5,"cap":500,"notes":"5% automatically on your single highest eligible spend category each cycle"}],"welcomeOffer":{"description":"Cash bonus after minimum spend","spendRequirement":1500,"timeframeMonths":6},"benefits":[{"label":"Automatic category match","description":"No activation needed \u2014 5% applies automatically to your top category each cycle."}],"loungeAccess":[],"travelProtections":[],"transferPartnerIds":[],"eligibility":{"minCreditScoreBand":"good","minCreditAgeMonths":12,"maxRecentInquiries6mo":4,"incomeGuidance":"Steady income sufficient to cover a modest credit line.","issuerRules":["Citi generally limits new personal-card applications to roughly one per 8 days across all Citi cards."],"notes":"Pairs well with Double Cash for a simple two-card Citi setup."},"productChangeTargets":[],"applicationUrl":"https://www.citi.com/credit-cards/citi-custom-cash-credit-card","dataFreshness":{"lastVerified":"2025-06-01","source":"Issuer public product pages (manually compiled)","confidence":"medium"}}'::jsonb),
  ('citi_strata_premier', 'citi', 'Citi Strata Premier', 95, '{"id":"citi_strata_premier","name":"Citi Strata Premier","issuerId":"citi","network":"mastercard","category":["travel"],"annualFee":95,"rewardsCurrency":"citi_thankyou","baseRewardRate":1,"rewardCategories":[{"category":"travel","multiplier":3},{"category":"dining","multiplier":3},{"category":"groceries","multiplier":3},{"category":"gas","multiplier":3}],"welcomeOffer":{"description":"Large one-time bonus points after minimum spend","spendRequirement":4000,"timeframeMonths":3},"benefits":[{"label":"Broad 3x categories","description":"3x across travel, dining, groceries, and gas covers most everyday spend."}],"loungeAccess":[],"travelProtections":["Trip cancellation/interruption","Trip delay reimbursement"],"transferPartnerIds":["air_france_klm","jetblue","virgin_atlantic"],"eligibility":{"minCreditScoreBand":"good","minCreditAgeMonths":18,"maxRecentInquiries6mo":3,"incomeGuidance":"Income sufficient to comfortably justify a mid-tier travel card.","issuerRules":["Citi generally limits new personal-card applications to roughly one per 8 days across all Citi cards."],"notes":"Citi''s primary transferable-points travel card."},"productChangeTargets":[],"applicationUrl":"https://www.citi.com/credit-cards/citi-strata-premier-credit-card","dataFreshness":{"lastVerified":"2025-06-01","source":"Issuer public product pages (manually compiled)","confidence":"medium"}}'::jsonb),
  ('discover_it_student_cash_back', 'discover', 'Discover it Student Cash Back', 0, '{"id":"discover_it_student_cash_back","name":"Discover it Student Cash Back","issuerId":"discover","network":"discover","category":["student","cash_back"],"annualFee":0,"rewardsCurrency":"discover_cashback","baseRewardRate":1,"rewardCategories":[{"category":"rotating","multiplier":5,"cap":1500,"notes":"5% on quarterly-activated rotating categories"}],"welcomeOffer":{"description":"Discover matches all cash back earned in year one","spendRequirement":0,"timeframeMonths":12},"benefits":[{"label":"Cashback Match","description":"Discover automatically matches all cash back earned during the first 12 months."},{"label":"Good-grades reward","description":"Statement credit each school year for a GPA of 3.0 or higher, for up to five years."}],"loungeAccess":[],"travelProtections":[],"transferPartnerIds":[],"eligibility":{"minCreditScoreBand":"no_credit","minCreditAgeMonths":0,"maxRecentInquiries6mo":4,"incomeGuidance":"Student income (including allowance/part-time work) is generally acceptable.","issuerRules":["Discover generally allows only one Discover card per person at a time."],"notes":"One of the most accessible first cards for students with no prior credit history."},"productChangeTargets":["discover_it_cash_back"],"applicationUrl":"https://www.discover.com/credit-cards/student/","dataFreshness":{"lastVerified":"2025-06-01","source":"Issuer public product pages (manually compiled)","confidence":"medium"}}'::jsonb),
  ('discover_it_cash_back', 'discover', 'Discover it Cash Back', 0, '{"id":"discover_it_cash_back","name":"Discover it Cash Back","issuerId":"discover","network":"discover","category":["cash_back"],"annualFee":0,"rewardsCurrency":"discover_cashback","baseRewardRate":1,"rewardCategories":[{"category":"rotating","multiplier":5,"cap":1500,"notes":"5% on quarterly-activated rotating categories"}],"welcomeOffer":{"description":"Discover matches all cash back earned in year one","spendRequirement":0,"timeframeMonths":12},"benefits":[{"label":"Cashback Match","description":"Discover automatically matches all cash back earned during the first 12 months."}],"loungeAccess":[],"travelProtections":[],"transferPartnerIds":[],"eligibility":{"minCreditScoreBand":"fair","minCreditAgeMonths":6,"maxRecentInquiries6mo":4,"incomeGuidance":"Steady income sufficient to cover a modest credit line.","issuerRules":["Discover generally allows only one Discover card per person at a time."],"notes":"A strong no-annual-fee option for rotating-category spenders."},"productChangeTargets":[],"applicationUrl":"https://www.discover.com/credit-cards/cash-back/","dataFreshness":{"lastVerified":"2025-06-01","source":"Issuer public product pages (manually compiled)","confidence":"medium"}}'::jsonb),
  ('boa_customized_cash_rewards', 'bank_of_america', 'Bank of America Customized Cash Rewards', 0, '{"id":"boa_customized_cash_rewards","name":"Bank of America Customized Cash Rewards","issuerId":"bank_of_america","network":"visa","category":["cash_back"],"annualFee":0,"rewardsCurrency":"cashback","baseRewardRate":1,"rewardCategories":[{"category":"choice_category","multiplier":3,"cap":2500,"notes":"3% in a category you choose (gas, online shopping, dining, travel, drugstore, home improvement/furnishings)"},{"category":"groceries","multiplier":2,"cap":2500}],"welcomeOffer":{"description":"Cash bonus after minimum spend","spendRequirement":1000,"timeframeMonths":3},"benefits":[{"label":"Preferred Rewards boost","description":"Existing Bank of America/Merrill banking relationships can boost rewards by 25\u201375%."}],"loungeAccess":[],"travelProtections":[],"transferPartnerIds":[],"eligibility":{"minCreditScoreBand":"good","minCreditAgeMonths":12,"maxRecentInquiries6mo":4,"incomeGuidance":"Steady income sufficient to cover a modest credit line.","issuerRules":["Subject to Bank of America''s informal 2/3/4 application-velocity rule."],"notes":"Rewards scale up meaningfully for existing Bank of America banking customers."},"productChangeTargets":[],"applicationUrl":"https://www.bankofamerica.com/credit-cards/products/customized-cash-back-credit-card/","dataFreshness":{"lastVerified":"2025-06-01","source":"Issuer public product pages (manually compiled)","confidence":"medium"}}'::jsonb),
  ('boa_premium_rewards', 'bank_of_america', 'Bank of America Premium Rewards', 95, '{"id":"boa_premium_rewards","name":"Bank of America Premium Rewards","issuerId":"bank_of_america","network":"visa","category":["travel"],"annualFee":95,"rewardsCurrency":"cashback","baseRewardRate":1.5,"rewardCategories":[{"category":"travel","multiplier":2},{"category":"dining","multiplier":2}],"welcomeOffer":{"description":"Cash bonus after minimum spend","spendRequirement":2000,"timeframeMonths":3},"benefits":[{"label":"$100 annual travel/incidental credit","description":"Statement credit toward airline incidentals or travel purchases."},{"label":"Preferred Rewards boost","description":"Existing banking relationships can boost rewards by 25\u201375%."}],"loungeAccess":[],"travelProtections":["Trip cancellation/interruption","Baggage delay insurance"],"transferPartnerIds":[],"eligibility":{"minCreditScoreBand":"good","minCreditAgeMonths":18,"maxRecentInquiries6mo":3,"incomeGuidance":"Income sufficient to comfortably justify a mid-tier travel card.","issuerRules":["Subject to Bank of America''s informal 2/3/4 application-velocity rule."],"notes":"Strongest for existing Bank of America/Merrill Preferred Rewards members."},"productChangeTargets":[],"applicationUrl":"https://www.bankofamerica.com/credit-cards/products/premium-rewards-credit-card/","dataFreshness":{"lastVerified":"2025-06-01","source":"Issuer public product pages (manually compiled)","confidence":"medium"}}'::jsonb),
  ('wells_fargo_active_cash', 'wells_fargo', 'Wells Fargo Active Cash', 0, '{"id":"wells_fargo_active_cash","name":"Wells Fargo Active Cash","issuerId":"wells_fargo","network":"visa","category":["cash_back"],"annualFee":0,"rewardsCurrency":"wells_fargo_rewards","baseRewardRate":2,"rewardCategories":[{"category":"everything","multiplier":2}],"welcomeOffer":{"description":"Cash bonus after minimum spend","spendRequirement":500,"timeframeMonths":3},"benefits":[{"label":"Simple flat 2%","description":"No annual fee, no categories to track."}],"loungeAccess":[],"travelProtections":["Cell phone protection"],"transferPartnerIds":[],"eligibility":{"minCreditScoreBand":"good","minCreditAgeMonths":12,"maxRecentInquiries6mo":4,"incomeGuidance":"Steady income sufficient to cover a modest credit line.","issuerRules":["Wells Fargo generally allows only one new personal card application every 6 months."],"notes":"A strong flat-rate keeper and a low-friction way to start a Wells Fargo relationship."},"productChangeTargets":[],"applicationUrl":"https://www.wellsfargo.com/credit-cards/active-cash/","dataFreshness":{"lastVerified":"2025-06-01","source":"Issuer public product pages (manually compiled)","confidence":"medium"}}'::jsonb),
  ('wells_fargo_autograph', 'wells_fargo', 'Wells Fargo Autograph', 0, '{"id":"wells_fargo_autograph","name":"Wells Fargo Autograph","issuerId":"wells_fargo","network":"visa","category":["travel"],"annualFee":0,"rewardsCurrency":"wells_fargo_rewards","baseRewardRate":1,"rewardCategories":[{"category":"travel","multiplier":3},{"category":"dining","multiplier":3},{"category":"gas","multiplier":3},{"category":"streaming","multiplier":3}],"welcomeOffer":{"description":"Cash bonus (as points) after minimum spend","spendRequirement":1000,"timeframeMonths":3},"benefits":[{"label":"No annual fee travel earner","description":"3x across a broad set of everyday categories with no annual fee."}],"loungeAccess":[],"travelProtections":["Cell phone protection"],"transferPartnerIds":[],"eligibility":{"minCreditScoreBand":"good","minCreditAgeMonths":12,"maxRecentInquiries6mo":4,"incomeGuidance":"Steady income sufficient to cover a modest credit line.","issuerRules":["Wells Fargo generally allows only one new personal card application every 6 months."],"notes":"Pairs well with Active Cash for a simple two-card Wells Fargo setup."},"productChangeTargets":[],"applicationUrl":"https://www.wellsfargo.com/credit-cards/autograph/","dataFreshness":{"lastVerified":"2025-06-01","source":"Issuer public product pages (manually compiled)","confidence":"medium"}}'::jsonb),
  ('usbank_altitude_go', 'us_bank', 'U.S. Bank Altitude Go', 0, '{"id":"usbank_altitude_go","name":"U.S. Bank Altitude Go","issuerId":"us_bank","network":"visa","category":["cash_back"],"annualFee":0,"rewardsCurrency":"usbank_points","baseRewardRate":1,"rewardCategories":[{"category":"dining","multiplier":4},{"category":"groceries","multiplier":2},{"category":"gas","multiplier":2},{"category":"streaming","multiplier":2}],"welcomeOffer":{"description":"Bonus points after minimum spend","spendRequirement":1000,"timeframeMonths":3},"benefits":[{"label":"No annual fee dining earner","description":"4x on dining including takeout and delivery, with no annual fee."}],"loungeAccess":[],"travelProtections":[],"transferPartnerIds":[],"eligibility":{"minCreditScoreBand":"good","minCreditAgeMonths":12,"maxRecentInquiries6mo":4,"incomeGuidance":"Steady income sufficient to cover a modest credit line.","issuerRules":["U.S. Bank evaluates recent inquiries and existing relationship depth on every application."],"notes":"A solid dining-focused no-fee card, especially with an existing U.S. Bank relationship."},"productChangeTargets":["usbank_altitude_reserve"],"applicationUrl":"https://www.usbank.com/credit-cards/altitude-go-visa-signature-credit-card.html","dataFreshness":{"lastVerified":"2025-06-01","source":"Issuer public product pages (manually compiled)","confidence":"medium"}}'::jsonb),
  ('usbank_altitude_reserve', 'us_bank', 'U.S. Bank Altitude Reserve', 400, '{"id":"usbank_altitude_reserve","name":"U.S. Bank Altitude Reserve","issuerId":"us_bank","network":"visa","category":["premium_travel"],"annualFee":400,"rewardsCurrency":"usbank_points","baseRewardRate":1,"rewardCategories":[{"category":"travel_and_mobile_wallet","multiplier":3},{"category":"everything","multiplier":1.5}],"welcomeOffer":{"description":"Large one-time bonus points after minimum spend","spendRequirement":4500,"timeframeMonths":3},"benefits":[{"label":"$325 annual travel/dining credit","description":"Broad statement credit toward travel and eligible dining purchases."},{"label":"Priority Pass lounge access","description":"Includes Priority Pass Select membership."}],"loungeAccess":["Priority Pass"],"travelProtections":["Trip cancellation/interruption","Cell phone protection"],"transferPartnerIds":[],"eligibility":{"minCreditScoreBand":"very_good","minCreditAgeMonths":36,"maxRecentInquiries6mo":2,"incomeGuidance":"Income that comfortably supports a premium annual fee.","issuerRules":["U.S. Bank evaluates recent inquiries and existing relationship depth on every application."],"notes":"Effective annual cost is often near $75 after the travel/dining credit for those who use it fully."},"productChangeTargets":[],"applicationUrl":"https://www.usbank.com/credit-cards/altitude-reserve-visa-infinite-credit-card.html","dataFreshness":{"lastVerified":"2025-06-01","source":"Issuer public product pages (manually compiled)","confidence":"medium"}}'::jsonb)
on conflict (id) do update set issuer_id = excluded.issuer_id, name = excluded.name, annual_fee = excluded.annual_fee, product = excluded.product;
